apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-deployment
  namespace: thumbnail-service
  labels:
    app: thumbnail-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thumbnail-service-app
  template:
    metadata:
      labels:
        app: thumbnail-service-app
    spec:
      containers:
      - name: thumbnail-service-app
        image: 480935361548.dkr.ecr.us-east-1.amazonaws.com/thumbnail-service:latest
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux