apiVersion: v1
kind: Service
metadata:
  name: ts-service
  namespace: thumbnail-service
spec:
  type: LoadBalancer
  selector:
    app: thumbnail-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080